### ISSUE TITLE
crash when changing cover image

### ISSUE THREAD

**Issue by 1138-thx** [VinylMusicPlayer/VinylMusicPlayer#1076] opened 2024-05-08 12:12 UTC
**Describe the bug**
Vinyl Music Player crashes when I try to change a cover image for an album.

**To reproduce**
1. Go to 'tag-editor'
2. Click on 'image'
3. Click on 'get image from drive' or 'SD-card' or whatever 
4. Choose image
5. Crash

**Expected behavior**
A new cover image is saved in every song file
for the chosen album

**Device Info**
App version: 1.10.2
App version code: 199
Android build version: 84bdac565a
Android release version: 11
Android SDK version: 30
Android build ID: lineage_gemini-userdebug 11 RQ3A.211001.001 84bdac565a
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: gemini
Device model: MI 5
Device product name: gemini
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

## Time: 
2024/05/08 14:02:13
## Stack: 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/imageio/ImageIO;
	at org.jaudiotagger.tag.images.StandardArtwork.getImage(Unknown Source:9)
	at org.jaudiotagger.tag.images.StandardArtwork.setImageFromData(Unknown Source:0)
	at org.jaudiotagger.tag.flac.FlacTag.createField(SourceFile:3)
	at org.jaudiotagger.tag.flac.FlacTag.setField(SourceFile:4)
	at com.poupa.vinylmusicplayer.ui.activities.tageditor.AbsTagEditorActivity$AsyncTask.doInBackground(SourceFile:2)
	at com.poupa.vinylmusicplayer.ui.activities.tageditor.AbsTagEditorActivity$AsyncTask.doInBackground(SourceFile:1)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more
Caused by: java.lang.ClassNotFoundException: javax.imageio.ImageIO
	... 12 more

**Comment by soncaokim** [comment] 2024-05-10 12:56
Duplicate of https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/891

**Closed by soncaokim** 2024-05-10 12:56 UTC
Labels: bug
