### ISSUE TITLE
Crashes on Android 13, possibly linked to the use of widget

### ISSUE THREAD

**Issue by teackot** [VinylMusicPlayer/VinylMusicPlayer#638] opened 2023-01-22 11:18 UTC
**Describe the bug**
Just updated my Pixel 6 to Android 13 and can't open the app anymore because it crashes instantly. I can start the music from android media controls though.

**To Reproduce**
1. update to Android 13
2. open the app

**Smartphone**
 - Device: Google Pixel 6
 - Android Version: 13
 - Vinyl Music Player Version: 1.3.0

**Comment by gaycodegal** [comment] 2023-01-23 04:49
Sounds similar to https://github.com/AdrienPoupa/VinylMusicPlayer/issues/621#issuecomment-1302863205 

I think the intent logic should be the culprit, sometimes the app does not discard the active intent in the event of an app crash on intent open. Probably good to fix eventually but not in urgent need of fix because there is a workaround at the above comment. I have a pixel 6a on Android 13 and it works fine with is why I suspect the above issue is similar

**Comment by Octoton** [comment] 2023-01-26 11:56
You can try to clear cache and/or data for this app, could help
Be carefull, clearing data will no remove any music but all option you had setup will be clear (like you opened the app for the first time)

**Comment by soncaokim** [comment] 2023-02-07 08:45
Is this still a problem with the latest version of the app (v1.4.1)?

**Comment by teackot** [comment] 2023-02-07 12:58
> there is a workaround at the above comment

> You can try to clear cache and/or data for this app, could help

Cleaning the full data allowed me to enter the app, but clicking on any track (or shuffling like in the issue @gaycodegal linked) still crashes the app.

**Comment by teackot** [comment] 2023-02-07 12:59
> Is this still a problem with the latest version of the app (v1.4.1)?

Didn't update yet, I'll try that

**Comment by teackot** [comment] 2023-02-07 13:03
> Is this still a problem with the latest version of the app (v1.4.1)?

Nope, fixed, thanks!

**Comment by teackot** [comment] 2023-02-09 13:44
No, not fixed. It worked fine for a while after I reinstalled the app from F-Droid, but it started crashing again.

But now I have some new details: I uninstalled the Google Play version and installed the new one from F-Droid. Turns out the issue disappeared because the home screen widget got removed and as soon as I added it back the app started crashing again.

**Comment by topas-rec** [comment] 2023-03-02 08:21
Experience crashes on Android 13 (LineageOS 20).
Opening the app makes it freeze after a second.
After resetting it, it freezes while scanning songs. (Always at the same song number)

I had this issue a few weeks ago and wad able to get around it after clearing cache or clearing storage or even uninstalling, but I can't remember what exactly.
Currently clearing cash, clearing storage and uninstalling doesn't help.
Downgrading from FDroid also doesn't help. (Tried all threw available versions down to 1.3.0)

I was able to fix it by installing the google play version, which is currently 1.3.0.

**Comment by topas-rec** [comment] 2023-03-05 09:04
Tried to get logs from logcat today using adb and USB debugging and **the app did not crash or freeze at all**.

**Comment by xeYe-org** [comment] 2023-03-05 17:38
Not sure it's the issue I am facing since the update to Android 13.
I can reproduce an immediate crash when I have widget #4 (big cover image) active after opening the player. Didn't crash on me with the other widget types so far.

Might this be the reason?
`Caused by: java.lang.IllegalArgumentException: RemoteViews for widget update exceeds maximum bitmap memory usage (used: 18757656, max: 16329600)
`
Crash report attached, with VinylMusicPlayer 1.5 build from a few days ago
[crashreport.txt](https://github.com/VinylMusicPlayer/VinylMusicPlayer/files/10892414/crashreport.txt)

**Comment by soncaokim** [comment] 2023-10-13 22:33
Might be related to https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/789, which is fixed.
I'm closing this fow now, please reopen this if it's not fixed

**Closed by soncaokim** 2023-10-13 22:33 UTC
Labels: bug
