### ISSUE TITLE
Crash on track removal from playlust

### ISSUE THREAD

**Issue by bell07** [VinylMusicPlayer/VinylMusicPlayer#917] opened 2024-01-15 06:41 UTC
**Describe the bug**

**To reproduce**
1. Appears on track removal from current queue
2. no idea how to reproduce. If I clear the queue and add the same tracks, issue does not appear anymore

**Device info**
Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

 - Device: 
 - Android Version:
 - ROM:
 - Vinyl Music Player Version:

**Additional context**
App version: 1.6.3
App version code: 189
Android build version: 9d952b5f6b
Android release version: 13
Android SDK version: 33
Android build ID: lineage_sake-userdebug 13 TQ3A.230901.001 9d952b5f6b
Device brand: asus
Device manufacturer: asus
Device name: ASUS_I006D
Device model: ASUS_I006D
Device product name: WW_I006D
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

## Time: 
2024/01/15 07:32:02
## Stack: 
java.lang.IllegalArgumentException: Bad index=-1
	at com.poupa.vinylmusicplayer.misc.queue.StaticPlayingQueue.updateQueueIndexesAfterSongsModification(SourceFile:2)
	at com.poupa.vinylmusicplayer.misc.queue.StaticPlayingQueue.remove(Unknown Source:19)
	at com.poupa.vinylmusicplayer.service.MusicService.removeSong(Unknown Source:19)
	at com.poupa.vinylmusicplayer.helper.MusicPlayerRemote.removeFromQueue(SourceFile:1)
	at com.poupa.vinylmusicplayer.adapter.song.PlayingQueueAdapter$SwipedResultActionRemoveItem.onSlideAnimationEnd(Unknown Source:26)
	at com.h6ah4i.android.widget.advrecyclerview.swipeable.action.SwipeResultAction.slideAnimationEnd(Unknown Source:0)
	at com.h6ah4i.android.widget.advrecyclerview.swipeable.ItemSlidingAnimator$SlidingAnimatorListenerObject.onAnimationEnd(Unknown Source:49)
	at androidx.core.view.ViewPropertyAnimatorCompat$1.onAnimationEnd(Unknown Source:4)
	at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1115)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:600)
	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1333)
	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1575)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:328)
	at android.animation.AnimationHandler.-$$Nest$mdoAnimationFrame(Unknown Source:0)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:86)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:827)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by soncaokim** [comment] 2024-01-24 16:23
Does this issue happens when some played song (in the queue) has been removed from the device? Or the queue has been altered somehow?

**Comment by soncaokim** [comment] 2024-01-31 20:08
Looks like a duplicate of #778

**Closed by soncaokim** 2024-01-31 20:08 UTC
Labels: bug
