### ISSUE TITLE
Your app has not been granted the READ_MEDIA_AUDIO permission. 

### ISSUE THREAD

**Issue by HumanMus1c** [VinylMusicPlayer/VinylMusicPlayer#909] opened 2023-12-31 08:50 UTC
**Describe the bug**
When I try to add black-list folders to Library.
And ERROR pop up, said "Your app has not been granted the READ_MEDIA_AUDIO permission. "
![Screenshot_20231229_194156_com poupa vinylmusicplayer](https://github.com/VinylMusicPlayer/VinylMusicPlayer/assets/46023154/248bff1a-740d-48c5-bdbb-bc2661b50c3d)

**To reproduce**
1. Go to 'Settings-Blacklist'
2. Click on 'Add'
3. See error

**Expected behavior**
It supposes to show me file folder selector.

**Device info**
Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

 - Device: Huawei mate30 pro
 - Android Version: 12
 - ROM: HarmonyOS 4.0.0
 - Vinyl Music Player Version: 1.6.3

**Additional context**
In System settings - App manage - Vinyl - Permissions: "Media and Files" only have one option "Media only".

![Screenshot_20231229_194156_com poupa vinylmusicplayer](https://github.com/VinylMusicPlayer/VinylMusicPlayer/assets/46023154/0adf31ee-527b-46c8-9691-b81cfa2bc90b)
![Screenshot_20231231_162937_com android settings](https://github.com/VinylMusicPlayer/VinylMusicPlayer/assets/46023154/e80f05fa-eac8-460e-9aa1-3eb1353fc093)
![Screenshot_20231231_164208_com android permissioncontroller](https://github.com/VinylMusicPlayer/VinylMusicPlayer/assets/46023154/c785c967-e97b-454f-b2b8-7d1748f4caef)

**Comment by soncaokim** [comment] 2024-01-24 16:48
Duplicate of #916

**Closed by soncaokim** 2024-01-24 16:48 UTC
Labels: bug
