### ISSUE TITLE
Song Lockscreen Applet is Broken

### ISSUE THREAD

**Issue by UltimateCubchoo** [VinylMusicPlayer/VinylMusicPlayer#627] opened 2022-11-22 14:39 UTC
**Describe the bug**
The song displayed on the lock screen is one song behind. If you just start playing music then try viewing it on the lock screen the song listed is always before.

**To Reproduce**
1. Play a song
2. Shut screen off
3. Turn screen on

**Expected behavior**
The song updates when you skip a section of the song with the progress bar. I think it isn't updating properly when you skip and/or turn the screen on

**Screenshots**
![bug1](https://user-images.githubusercontent.com/84922468/203341517-a3053196-079e-4a0b-9ba6-3147c7362045.jpg)
![bug2](https://user-images.githubusercontent.com/84922468/203341531-03507b16-e954-49aa-8aab-2faefa70ffdc.jpg)

**Smartphone (please complete the following information):**
 - Device: Galaxy S10 Lite
 - Android Version: Andriod 12
 - ROM: OneUI
 - Vinyl Music Player Version: 1.3.0

**Additional context**
This becomes quite a hassle when running and biking.

**Comment by soncaokim** [comment] 2023-03-10 15:48
Hello, is this still happening with the app version 1.5.0?

Thanks

**Comment by soncaokim** [comment] 2023-07-08 13:53
Closing this, duplicate of #732

**Closed by soncaokim** 2023-07-08 13:53 UTC
Labels: bug
