### ISSUE TITLE
App Crashing - On library scan

### ISSUE THREAD

**Issue by t0fr** [VinylMusicPlayer/VinylMusicPlayer#831] opened 2023-10-26 11:51 UTC
**Describe the bug**
Crashes on library scan. Both on rescan, and initial scan on a fresh install (Google Play and Fdroid)

**Expected behavior**
Not to crash, and successfully scan library.

**Crash Log**

App version: 1.5.4
App version code: 183
Android build version: 10754064
Android release version: 14
Android SDK version: 34
Android build ID: UP1A.231005.007
Device brand: google
Device manufacturer: Google
Device name: oriole
Device model: Pixel 6
Device product name: oriole
Device hardware name: oriole
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

Time: Thu Oct 26 07:03:14 EDT 2023

Stack:
java.lang.IllegalStateException: Can't access ViewModels from detached fragment
	at androidx.fragment.app.Fragment.getViewModelStore(Unknown Source:35)
	at androidx.loader.app.LoaderManager.getInstance(Unknown Source:5)
	at com.poupa.vinylmusicplayer.ui.fragments.mainactivity.library.pager.SongsFragment.reload(Unknown Source:0)
	at com.poupa.vinylmusicplayer.discog.b.accept(Unknown Source:20)
	at com.poupa.vinylmusicplayer.helper.WeakMethodReference.run(Unknown Source:10)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

**Comment by soncaokim** [comment] 2023-10-26 12:01
Duplicate of https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/707.
This should be fixed with version 1.5.5 - please reopen if this is not the case. Thanks

**Closed by soncaokim** 2023-10-26 12:01 UTC
Labels: bug
