### ISSUE TITLE
Album Art on flac files

### ISSUE THREAD

**Issue by Schlautobahn** [VinylMusicPlayer/VinylMusicPlayer#1038] opened 2024-04-17 08:28 UTC
**Describe the bug**
App crashes when I try to save Album Art on flac files

**To reproduce**
1. Go to Album
2. Click on 'Tag Editor'
3. Choose Album Art
4. Click 'Save'
5. See error

**Device info**

 - Device: Poco F1
 - Android Version: 13
 - ROM: LineageOS 2020240202-microG-beryllium
 - Vinyl Music Player Version: 1.10.0

**Comment by Schlautobahn** [comment] 2024-04-17 08:32
App version: 1.10.0
App version code: 197
Android build version: eng.root.20240202.205748
Android release version: 13
Android SDK version: 33
Android build ID: lineage_beryllium-userdebug 13 TQ3A.230901.001 eng.root.20240202.205748 dev-keys
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: beryllium
Device model: POCO F1
Device product name: beryllium
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

## Time: 
2024/04/17 10:28:55
## Stack: 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/imageio/ImageIO;
	at org.jaudiotagger.tag.images.StandardArtwork.getImage(Unknown Source:9)
	at org.jaudiotagger.tag.images.StandardArtwork.setImageFromData(Unknown Source:0)
	at org.jaudiotagger.tag.flac.FlacTag.createField(SourceFile:3)
	at org.jaudiotagger.tag.flac.FlacTag.setField(SourceFile:4)
	at com.poupa.vinylmusicplayer.ui.activities.tageditor.AbsTagEditorActivity$AsyncTask.doInBackground(SourceFile:2)
	at com.poupa.vinylmusicplayer.ui.activities.tageditor.AbsTagEditorActivity$AsyncTask.doInBackground(SourceFile:1)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 4 more
Caused by: java.lang.ClassNotFoundException: javax.imageio.ImageIO
	... 12 more

**Comment by Schlautobahn** [comment] 2024-04-17 08:32
App version: 1.10.0
App version code: 197
Android build version: eng.root.20240202.205748
Android release version: 13
Android SDK version: 33
Android build ID: lineage_beryllium-userdebug 13 TQ3A.230901.001 eng.root.20240202.205748 dev-keys
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: beryllium
Device model: POCO F1
Device product name: beryllium
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

## Time: 
2024/04/17 10:28:55
## Stack: 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/imageio/ImageIO;
	at org.jaudiotagger.tag.images.StandardArtwork.getImage(Unknown Source:9)
	at org.jaudiotagger.tag.images.StandardArtwork.setImageFromData(Unknown Source:0)
	at org.jaudiotagger.tag.flac.FlacTag.createField(SourceFile:3)
	at org.jaudiotagger.tag.flac.FlacTag.setField(SourceFile:4)
	at com.poupa.vinylmusicplayer.ui.activities.tageditor.AbsTagEditorActivity$AsyncTask.doInBackground(SourceFile:2)
	at com.poupa.vinylmusicplayer.ui.activities.tageditor.AbsTagEditorActivity$AsyncTask.doInBackground(SourceFile:1)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 4 more
Caused by: java.lang.ClassNotFoundException: javax.imageio.ImageIO
	... 12 more

**Comment by soncaokim** [comment] 2024-04-23 13:05
Duplicate of #891

**Closed by soncaokim** 2024-04-23 13:05 UTC
Labels: bug
