### ISSUE TITLE
Folder cover image not loaded

### ISSUE THREAD

**Issue by soncaokim** [VinylMusicPlayer/VinylMusicPlayer#816] opened 2023-10-18 10:49 UTC
Folder cover image (not the embedded album art) is not loaded anymore since version 1.5.3 (Android 13 upgrade)

Originally reported in #788

**Comment by soncaokim** [comment] 2023-10-21 13:02
Hello @mikelpr, I cannot reproduce this with the latest version (1.5.5, submitted to PlayStore).
Tested with a cover.jpg in the album folder.
Do you mind re-checking and report back your observation?

**Comment by rkerschn** [comment] 2023-10-24 09:38
I can confirm this issue, no cover art is loaded.

cover art file: folder.jpg
System: Android 13

Version 1.5.2 is the last one working, I have tried 1.5.3 to 1.5.5

**Comment by fwsmit** [comment] 2023-10-26 11:47
I can also reproduce this issue on version 1.5.5. Let me know if you need any more information on this issue

**Comment by soncaokim** [comment] 2023-10-26 13:12
Can you guys help me to clarify one thing? Are you all using Folder views, not the Library view?

**Comment by fwsmit** [comment] 2023-10-26 17:07
I'm using library view. I just installed the app, so I didn't change any settings.

**Comment by fwsmit** [comment] 2023-10-26 23:07
The PR says it fixes folder view, not library view

**Comment by soncaokim** [comment] 2023-10-26 23:12
> The PR says it fixes folder view, not library view

Oops, you are right, I didn't read your reply correctly

**Comment by soncaokim** [comment] 2023-10-27 07:31
> I'm using library view. I just installed the app, so I didn't change any settings.

@fwsmit Can you please share me a screenshot of your settings, as well as a sample folder (track + cover file) that you expect to function properly?

**Comment by rkerschn** [comment] 2023-10-27 08:02
@soncaokim 
For me it is also library view, folder view does not work at all, just tried.
Folder view only shows "Empty" and when trying to scan in ROOT/STORAGE/EMULATED/0/MUSIC it says "nothing to scan"

Btw, maybe it is related, rescanning the library takes ages with about 3 Songs per Second instead of the almost instant scan running through all the files. This also holds true when installing Vinyl after uninstall or after first install. This also began with 1.5.3.
No issues with 1.5.2

**Comment by soncaokim** [comment] 2023-10-27 08:52
> @soncaokim For me it is also library view, folder view does not work at all, just tried. Folder view only shows "Empty" and when trying to scan in ROOT/STORAGE/EMULATED/0/MUSIC it says "nothing to scan"

This is a separated problem, already reported (and I cannot reproduce, need to find a way to gather more info).

> Btw, maybe it is related, rescanning the library takes ages with about 3 Songs per Second instead of the almost instant scan running through all the files. This also holds true when installing Vinyl after uninstall or after first install. This also began with 1.5.3. No issues with 1.5.2

Yes, I needed to change the way the embedded cover image are extracted from track data - to support Android 13. For now I want to concentrate on bugs first, will need to revisit that for performance after.

> Rescanning throws this error: java.lang.NullPointerException: Can't toast on a thread that has not called Looper.prepare() at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:167) at android.widget.Toast.getLooper(Toast.java:185) at android.widget.Toast.(Toast.java:170) at android.widget.Toast.makeText(Toast.java:498) at android.widget.Toast.makeText(Toast.java:486) at com.poupa.vinylmusicplayer.discog.tagging.TagExtractor.extractTags(Unknown Source:25) at com.poupa.vinylmusicplayer.discog.Discography.addSong(Unknown Source:23) at 

Will have a look on this "toast" error. Do you mind open a new issue for this?

**Comment by rkerschn** [comment] 2023-10-27 09:44
@soncaokim
about reproducing the errors, may I ask, what phone and Android Brand (Samsung, Sony, Vanilla, LineageOs,...) and Version are you using?
I am on LineageOS 20 (Android 13) as well as on Oneplus OxygenOS 13.1 (Android 13)

Files I am using are .flac, if it is of relevance
Folder Structure:
/Music/FLAC/Artist/Album/*.flac (with id3 tags) + folder.jpg

About the "toast" error, sure, will open a new issue late this day or weekend.

**Comment by soncaokim** [comment] 2023-10-27 13:18
> Here is an example of an album where the album art didn't load (and it did load in phonograph). I removed every song except one to get under the size limit, but that shouldn't affect testing. I also didn't change any settings, except for dark mode.
> 
> [Mac Miller.zip](https://github.com/VinylMusicPlayer/VinylMusicPlayer/files/13187436/Mac.Miller.zip)

I've reproduced the error with this sample, on my real device but not on the emulator (!!!)

With some more instrumentation: the app failed to load the `.jpg` file with `FileNotFoundException: .../Mac.Miller/Mac Miller/Circles/folder.jpg: EACCESS (Permission denied)`

**Comment by fwsmit** [comment] 2023-10-27 14:37
Did you put the Mac Miller directory in the Mac.miller directory? I use a directory like Music/Mac Miller/Album/

**Comment by fwsmit** [comment] 2023-10-27 14:40
From the above error seems like vinyl is trying to open the right file, but doesn't get permission. That's weird, since at least on my device it has storage permissions

**Comment by soncaokim** [comment] 2023-10-27 15:19
@fwsmit and all: Thanks for your help here.

**The background**:
To support Android 13, we had to drop some storage permission. A13 restricted the raw storage access, and unfortunately we rely a lot on this - to load the metadata, to load the cover art, to fallback on the folder.jpg, to browse the folder/files.

To circumvent, we've add new workflows to gain the user explicit permission on the folder containing the music.
We've probably overlooked and missed some cases. The PR #832 brings some corrections.

**The hypothesis** I'm considering:
For some reason, the app dont get the user permission on the folder.jpg.
Either because you havent granted it, and we've missed the cases where we should have asked you that.
Or the granted permission doesnt cover new folders/files, or doesnt cover non-audio files.

**The help I need**:
If possible, can you please reset the app (remove storage/cache)
Then go through the welcome screen, grant all audio/media permission.
_Important_: Then try to simulate a song delete - i.e. not actually delete it, but just trigger the permission workflow via which you grant the app access to your music folders (the one containing Mac.Miller in the previous example).
--> Is the folder.jpg gets loaded (in the Library view and in Folders view) for the song that doesnt have embedded cover?

**Comment by fwsmit** [comment] 2023-10-27 16:08
Thank you for looking into this issue!

> **The help I need**: If possible, can you please reset the app (remove storage/cache) Then go through the welcome screen, grant all audio/media permission. _Important_: Then try to simulate a song delete - i.e. not actually delete it, but just trigger the permission workflow via which you grant the app access to your music folders (the one containing Mac.Miller in the previous example). --> Is the folder.jpg gets loaded (in the Library view and in Folders view) for the song that doesnt have embedded cover?

I have some questions regarding the testing. Should we test the latest master? If so, where can I download it? 
The other question is, how do I trigger the permission workflow for deletion? Do I just need to click delete from device and then cancel? For me it would not be an issue to just delete a song, since I can easily sync it back.

> **The background**: To support Android 13, we had to drop some storage permission. A13 restricted the raw storage access, and unfortunately we rely a lot on this - to load the metadata, to load the cover art, to fallback on the folder.jpg, to browse the folder/files.

Does the new way of storage permissions work on older versions of android?

**Comment by soncaokim** [comment] 2023-10-27 16:39
> Should we test the latest master? If so, where can I download it? 

In the front page of this repo, you have the "pre-release" link that points to the latest master.
Otherwise, here you go: https://github.com/VinylMusicPlayer/VinylMusicPlayer/releases/tag/pre-release

> The other question is, how do I trigger the permission workflow for deletion? Do I just need to click delete from device and then cancel? For me it would not be an issue to just delete a song, since I can easily sync it back.

Yes, please select the menu next to a song -> Delete from device.
Once you granted the folder permission (please select the parent folder of all your music), you should have a prompt to confirm the deletion of the song.

> Does the new way of storage permissions work on older versions of android?

Well, it should. Unless us stupid developers failed to cover all cases.

A13 just enforces something they introduced way back but we opted not to follow (since a lot of code change and horrible workflow).
Now we are forced to go their way, otherwise no clearance to publish to PlayStore. That explains, partly, the hiatus on PlayStore in the past year(s).

**Comment by secure-username** [comment] 2023-10-27 20:46
I just installed the pre-release 39b9b10 and tried the test you described @soncaokim.

OnePlus 7 Pro
Lineage OS 20 (Android 13)

After giving Vinyl access to my library directory, it still could not load any of my folder.jpg's.

**Comment by soncaokim** [comment] 2023-10-28 08:17
> After giving Vinyl access to my library directory, it still could not load any of my folder.jpg's.

But you do have the ability to browse through the songs, correct? Both in Library view and Folders view?

Thanks

**Comment by secure-username** [comment] 2023-10-28 12:18
> > After giving Vinyl access to my library directory, it still could not load any of my folder.jpg's.
> 
> But you do have the ability to browse through the songs, correct? Both in Library view and Folders view?
> 
> Thanks

I could already browse through songs in both Library and Folders views before I granted access to attempt to delete a song.

**Comment by soncaokim** [comment] 2023-11-06 16:39
Thanks Clément,

There is a known trouble where album cover art inside the album folder is not loaded (the EACCESS error mentioned in this thread). I'm looking into it when time allows.

To help, can you please isolate an album/a song that worked before but not in the 1.5.6 version and share it, so that I can have a look if I've overlooked anything?

For the artist cover, please open another issue.

**Comment by DeathTBO** [comment] 2023-11-06 21:20
Hello, so I have a very large library of 6.5k songs, and this is all on the internal storage of my S22. every album folder has a "Folder.jpg" (or the occasional png). None of these load. There are a handful of songs with the album art embedded in the song, and those load just fine. I just upgraded to 1.5.6, and then noticed it was still not loading the album art. So I followed some advice I read earlier, and uninstalled/reinstalled.

After finishing the library scan, I attempted to delete a song and it triggered the storage request. I selected my root music folder. Still was not showing the album art, so I rescanned again. Still nothing.

java.io.FileNotFoundException: /storage/emulated/0/Music/Tool/ænima/folder.jpg: open failed: EACCES (Permission denied)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at com.poupa.vinylmusicplayer.glide.audiocover.AbsCoverFetcher.fallback(Unknown Source:25)
	at com.poupa.vinylmusicplayer.glide.audiocover.AbsCoverFetcher.fallback(Unknown Source:5)
	at com.poupa.vinylmusicplayer.glide.audiocover.SongCoverFetcher.loadData(Unknown Source:47)
	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(Unknown Source:15)
	at com.bumptech.glide.load.engine.SourceGenerator.startNext(Unknown Source:97)
	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(Unknown Source:23)
	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(Unknown Source:59)
	at com.bumptech.glide.load.engine.DecodeJob.run(Unknown Source:29)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(Unknown Source:31)
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8624)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 13 more

**Comment by soncaokim** [comment] 2023-11-06 21:43
Thanks for testing @DeathTBO . I am able to reproduce this error.

**Comment by jistr** [comment] 2023-11-14 23:45
I had this issue with version 1.5.5. I did "force stop", "clear cache", "clear storage", uninstall, reinstall, and the problem disappeared. I think previously i tried just "force stop", "clear cache", "clear storage" and that didn't help.

Also, at the time this cover image problem was happening, i was able to see all music in Library view, but nothing was visible in Folders view at all.

**Comment by soncaokim** [comment] 2023-12-08 14:23
> Hi, I was wondering what the status is on this issue. As far as I understand, the issue has been reproduced. What still needs to be done to fix it?

Hi, short answer is there is no fix (yet).
The long answer: I'm still bugged on why, with all the requested permission granted, the app manages to open the audio track (scanning tags), browse the folder structure, but not able to open the external files residing on the same folder (cover image or the external lyrics, reported in #878). And I havent had the time to investigate further neither.

**Comment by soncaokim** [comment] 2023-12-16 08:57
I've just changed the phone and oddly enough, the folder.jpg cover image gets loaded fine.

The working OS for me is Android 13 with OnePlus layer.
The non-working OS is Android 13 with Lineage layer.

**Comment by mikelpr** [comment] 2024-02-10 00:27
On 1.8.0 they're loading again as if this never happened :D

**Comment by soncaokim** [comment] 2024-02-10 11:36
the only workaround I have right now is to use an external program (probably on your desktop) to embed the cover image in each track. With the size overhead.

**Comment by secure-username** [comment] 2024-02-18 02:28
@soncaokim Maybe this is solved by adding the `MANAGE_EXTERNAL_STORAGE` permission? I'm sure Google wouldn't like that on the store though. I'm willing to run a test build if you want to try it.

**Comment by soncaokim** [comment] 2024-02-26 15:52
> solved by adding the `MANAGE_EXTERNAL_STORAGE` permission

Hi, the whole bunch of regressions (external cover image, external lyrics, set as ring tone, static playlist) are due to precisely the removal of this very permission - which was asked for the previous versions of the app.

As you mentioned, Google doesnt like that. For the sake of privacy/user protection, they dont accept blanket permission like this one any more.

We had to remove it to be able to push back the app to the Play Store.

**Comment by rkerschn** [comment] 2024-02-26 15:56
I am asking myself what is so diffucult, because many other apps don't suffer from this issue, although they should have the same problems with removed permissions.

Since it still does not work with the lates version, I switched to "Metro - A music player for Android" from fdroid

**Comment by soncaokim** [comment] 2024-02-26 16:09
Good for you that you have a work around for your case. Many users dont use FDroid, that's why we need to play by G's PlayStore rule.

**Comment by DeathTBO** [comment] 2024-02-26 18:41
I understand that permission no longer exists, but there are new permissions to fill that gap. I see those permissions are already apart of Vinyl: "READ_MEDIA_IMAGES" and "READ_MEDIA_AUDIO".

Now what I don't understand, is why this permission is not working. The [documentation](https://developer.android.com/reference/android/Manifest.permission#READ_MEDIA_IMAGES) states that "READ_EXTERNAL_STORAGE" is still needed for API level 32 and below, but 33+ this permission does nothing. Only the READ_MEDIA_IMAGES is necessary.

I'm on Android 14, which is API level 34. Is there an error? Does this work for some people?

**Comment by DurotarHeights** [comment] 2024-03-13 21:11
Is there a way to download the google play signed version of 1.5.2? This version's AlbumArt works for me when sideloaded but Android Auto has problems loading the app this way.

**Comment by n2burns** [comment] 2024-03-15 04:18
> Is there a way to download the google play signed version of 1.5.2? This version's AlbumArt works for me when sideloaded but Android Auto has problems loading the app this way.

This really is not the right place to ask, but I'll answer anyways. The best solution is to enable [Developer Mode in Android Auto](https://9to5google.com/2023/01/25/how-to-enable-developer-mode-in-android-auto-and-why-you-might-want-to/) and use the apk from GitHub/f-droid. If you're insistent on using the Google signed apk, there are many easily found websites that provide these, none of which I'll link here.

**Comment by soncaokim** [comment] 2024-04-05 11:04
Looks like for the songs without embedded cover art, but with an external folder.jpg, Android MediaStore somehow manages to incorporate the cover art - and show it for instance in the delete confirmation popup if I request to delete the track.

I'll try to follow this lead, it may improve the support of folder cover image.

**Comment by soncaokim** [comment] 2024-04-06 12:01
I might have a fix here. Is there anyone (adventurous enough) who is willing to help by testing the development version?

Note that this is only a workaround, with limitations:
- it relies on MediaStore to scan the external cover image. So if MediaStore doesnt recognise the image, it will not work.
- only for Android Q+
- only work in Library view, not in Folder/SD Card views.

**Comment by soncaokim** [comment] 2024-04-06 14:06
> …until I saw that, mine being older I'm unable to

i'ill try to cover your case. Dont take that as a commitment though 😀

 Let's see how it turns out for now if I get feedback on Q+.

**Comment by DurotarHeights** [comment] 2024-04-06 15:15
> I might have a fix here. Is there anyone (adventurous enough) who is willing to help by testing the development version? #1022
> 
> Note that this is only a workaround, with limitations:
> 
> * it relies on MediaStore to scan the external cover image. So if MediaStore doesnt recognise the image, it will not work.
> * only for Android Q+
> * only work in Library view, not in Folder/SD Card views.

I can do it. Is this build available for download already? I don't see it.

**Comment by secure-username** [comment] 2024-04-06 15:44
You can get it from the CI run https://github.com/VinylMusicPlayer/VinylMusicPlayer/actions/runs/8580863571/job/23517340643?pr=1022

I just tried it and it works! I saw art on all of  my albums in library view. I did not have to rescan my library, they all showed up instantly.

Thanks @soncaokim!

**Comment by soncaokim** [comment] 2024-04-06 15:59
> I just tried it and it works!

Nice, thank for the quick feedback.

Android API and behaviour is horrible though :-/

**Comment by DurotarHeights** [comment] 2024-04-06 16:13
Looks fixed on a Galaxy S24 Ultra.

**Comment by soncaokim** [comment] 2024-04-06 16:20
Thanks @secure-username @DurotarHeights for the reaction.

@Porkepix Here is a new build that intends to cover your case (Android Q-) and should workfor Folder view as well
https://github.com/VinylMusicPlayer/VinylMusicPlayer/actions/runs/8582338042/artifacts/1390878500

Can you please confirm that's OK ?

**Comment by soncaokim** [comment] 2024-04-06 21:37
Hmm, I'm unable to reproduce the error on an emulator with Oreo.

**Comment by soncaokim** [comment] 2024-04-06 22:02
> Hmm, I'm unable to reproduce the error on an emulator with Oreo.

@Porkepix Is it possible for you to move some songs + it's folder.jpg to the main storage, i.e. to compare the behaviour with SD card vs with main storage?

@all I'd be interested in feedback from people with Android OS before Q, if you can help testing and share the resut that'll be helpful.

**Comment by soncaokim** [comment] 2024-04-11 11:48
Hi, thanks for investigating this. I'm looking at your logs now.

**Comment by soncaokim** [comment] 2024-04-11 13:58
The error (freeze on the splash screen) is here

> Reason: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{1116614 u0 com.poupa.vinylmusicplayer.ci/com.poupa.vinylmusicplayer.service.MusicService}

This is a regression due to this PR https://github.com/VinylMusicPlayer/VinylMusicPlayer/pull/978
It should happen when you have cleared the playing queue/or dont have any playing queue when you start the app.

I'm checking with the Android doc on how to fix the regression on the said PR, and will update.

**Closed** 2024-04-12 07:59 UTC
Labels: bug

**Comment by lucas-mior** [comment] 2024-11-05 12:39
If this is purely a permission issue, can there be 2 builds, one for fdroid and another for google play store?
