### ISSUE TITLE
Album art

### ISSUE THREAD

**Issue by comfortabletriphazard** [VinylMusicPlayer/VinylMusicPlayer#818] opened 2023-10-18 19:25 UTC
**Describe the bug**

Album art and all meta data art no longer appears. Some does but very few despite my entire library having art. 

**To reproduce**

Not too sure. I used the app for years and suddenly this has happened. I'm not sure if it's an update recently? I rescanned my library too but no luck. I also added a new song with album art which didn't render. 

**Expected behavior**

Album art displayed as appropriate with each song and album 

**Device info**
Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

 - Device: Motorola Edge 20 Pro
 - Android Version: 13
 - ROM: 
 - Vinyl Music Player Version: 1.5.4

**Additional context**

**Comment by soncaokim** [comment] 2023-10-19 13:11
What is the song format please (mp3, opus, flac etc)?
I'm assuming that's MP3 since it works for you previously. In that case, do you mind uploading a sample here so I can have a look?

**Comment by secure-username** [comment] 2023-10-27 20:25
> What is the song format please (mp3, opus, flac etc)? I'm assuming that's MP3 since it works for you previously. In that case, do you mind uploading a sample here so I can have a look?

I see the same issue on 1.5.5. I believe that Vinyl will not show album art for any audio file without an embedded image. I have a folder.jpg for almost all of my albums, but only the albums with embedded art show up in Vinyl.

I have 1 mp3 file with embedded art and 1 mp3 file without, and I only see art for the first one.

**Comment by comfortabletriphazard** [comment] 2023-10-27 20:42
Hey

I attached them previously, can you see them?

I'm attaching screenshots of the latest build on the Play Store which doesn't display art for the song but it does show that an image exists when you go into the tag editor.


I appreciate the experience you had too. I'm guessing it's a bug rather than needing a solution of embedding the image? I'm not sure if mine are embedded or not, I use a similar process for any songs I don't have art for, to give them art.

Kind Regards

Michael
________________________________

**Comment by secure-username** [comment] 2023-10-27 20:53
Oh it's definitely a bug that it won't show folder.jpg's, it was mentioned in [816](https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/816).

**Comment by comfortabletriphazard** [comment] 2023-10-27 20:55
Ah I noticed that reading the release notes haha. No worries. I love Vinyl it's an excellent app and looks fantastic with the art so great job to your team and hopefully this is an easy fix :)

Kind Regards

Michael
________________________________

**Comment by soncaokim** [comment] 2023-10-28 08:19
Indeed this is a duplicate of #816 (not falling back gracefully to folder.jpg if no embedded cover found).

**Closed by soncaokim** 2023-10-28 08:19 UTC
