### ISSUE TITLE
Notification not always lining up with current song

### ISSUE THREAD

**Issue by GraphicHealer** [VinylMusicPlayer/VinylMusicPlayer#962] opened 2024-02-28 13:20 UTC
**Describe the bug**
Sometimes when I'm playing my music, I'll swipe down to look at the notification, and it shows the previous song instead of the current song. Here are some screenshots.

![Screenshot_20240228-081459_Vinyl Music Player.png](https://github.com/VinylMusicPlayer/VinylMusicPlayer/assets/20365116/6cf4864e-8ba5-47c3-9315-bb5efce27d43)

![Screenshot_20240228-081501_Vinyl Music Player.png](https://github.com/VinylMusicPlayer/VinylMusicPlayer/assets/20365116/4007c630-0ef9-46ab-a6f3-2a3ea8878945)

**To reproduce**
1. Open vinyl music player
2. Play a playlist or album
3. Hit the next button and check the notification shade
4. Repeat step 3 until issue shows

**Expected behavior**
The notification should always line up with the current playing song.

**Device info**

 - Device: Pixel 7 Pro
 - Android Version: 13
 - ROM: CRDroid
 - Vinyl Music Player Version: 1.8.0

**Comment by soncaokim** [comment] 2024-02-28 13:26
Duplicate of #631

**Closed by soncaokim** 2024-02-28 13:26 UTC
Labels: bug
