### ISSUE TITLE
Reload library bug

### ISSUE THREAD

**Issue by bell07** [VinylMusicPlayer/VinylMusicPlayer#844] opened 2023-11-03 07:24 UTC
**Describe the bug**
Today I updated my mp3 collection and did a library reload. During reload an "share" popup appears with dump informations, pasted bellow. The app is not crashed but continued the scan / update process.

```
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String org.jaudiotagger.tag.Tag.getFirst(org.jaudiotagger.tag.FieldKey)' on a null object reference
at com.poupa.vinylmusicplayer.discog.tagging.TagExtractor.lambda$static$0(Unknown Source:0)
at com.poupa.vinylmusicplayer.discog.tagging.TagExtractor.b(Unknown Source:0)
at com.poupa.vinylmusicplayer.discog.tagging.a.apply(Unknown Source:34)
at com.poupa.vinylmusicplayer.discog.tagging.TagExtractor.extractTags(Unknown Source:69)
at com.poupa.vinylmusicplayer.discog.Discography.addSong(Unknown Source:23)
at com.poupa.vinylmusicplayer.discog.Discography.getOrAddSong(Unknown Source:40)
at com.poupa.vinylmusicplayer.discog.Discography.syncWithMediaStore(Unknown Source:78)
at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.doInBackground(Unknown Source:17)
at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.doInBackground(Unknown Source:2)
at android.os.AsyncTask$3.call(asynctask.java:394)
at [java.util.concurrent.](https://java.util.concurrent.futuretask.run/)[FutureTask](https://java.util.concurrent.futuretask.run/)[.run](https://java.util.concurrent.futuretask.run/)(futuretask.java:264)
at android.os.AsyncTask$SerialExecutor$[1](https://1.run/)[.run](https://1.run/)(asynctask.java:305)
at java.util.concurrent.ThreadPoolExecutor.runWorker(threadpoolexecutor.java:1137)
at java.util.concurrent.ThreadPoolExecutor$[Worker](https://worker.run/)[.run](https://worker.run/)(threadpoolexecutor.java:637)
at [java.lang.](https://java.lang.thread.run/)[Thread](https://java.lang.thread.run/)[.run](https://java.lang.thread.run/)(thread.java:1012)
```

**To reproduce**
1. Call "Rescan library"
2. Confirm the "Rescan can clear history" warning 

**Expected behavior**
The rescan should be processed without issues

**Device info**
 - Device: ASUS_I006D (ABIs: [arm64-v8a, armeabi-v7a, armeabi])
 - Android Version: 13 / SDK 33
 - ROM: lineage_sake-userdebug
 - Vinyl Music Player Version: 1.5.5

**Additional context**
Maybe the issue is related to #778 . Any "broken" Mp3 in my collection seems to cause issues.
Is any way to get the file name of the track that causes the issue?

**Comment by robotgoat** [comment] 2023-11-08 06:07
Hi, I'm receiving the same error when my music library is scanned. I think I narrowed down the issue to Vinyl being unable to read opus files properly. It tries to search for lyrics in the opus file and errors out. Can you confirm or replicate this with any opus files in your music library?

**Comment by robotgoat** [comment] 2023-11-08 06:49
I have a quick update: I did some troubleshooting and it seems that the error is not an embedded lyrics error. The error is coming from files without ID3 tags. In my case, my opus files did not have tags. I believe the format doesn't support metadata tagging to begin with. I converted them to mp3 with empty metadata fields and received the same error. I then populated the most basic metadata fields for ID3v2 (title and artist), and the error message went away. I wonder if this case handling for opus files and tagless audio files can be added in a future update.

**Comment by bell07** [comment] 2023-11-10 08:08
I do not have opus files. mp3's only.
Now I used EasyTAG and  found and fixed some crufty invalid tags. One file was containing year="2022-10-02".
Now the issue does not appear for me.
I think the error handling in reading the tags needs to be improved.

**Comment by XMA2l** [comment] 2023-12-14 16:36
For me all songs just become unplayable after rescan (a11 - fdroid - linux 3 kernel) 
On 1.5... All is fine - the nice way faster new 1.6.1 indexing seems to break it for me. Though it shredds speedwise - hope to see it working soon

**Comment by soncaokim** [comment] 2024-01-26 14:51
Should be a duplicate of #855 (fix will be available in the next release)

**Closed by soncaokim** 2024-01-26 14:51 UTC
Labels: bug
