### ISSUE TITLE
crash when unfavoriting song

### ISSUE THREAD

**Issue by pescepalla** [VinylMusicPlayer/VinylMusicPlayer#674] opened 2023-02-02 15:46 UTC
**Describe the bug**
App crashes if song is favorited, then unfavorited pressing the "heart" button top right.

**To reproduce**
1. Play a song
2. Press on "heart" button to favorite it
3. Press again to unfavorite it

**Expected behavior**
App should not crash but unfavorite the song

**Device info**
Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

 - Device:  fairphone 4
 - Android Version: 12
 - ROM: iodéos
 - Vinyl Music Player Version: 1.4.0

**Comment by soncaokim** [comment] 2023-02-07 08:43
Sorry, I cannot reproduce this bug. Do you have any further information on the problem (does it happen all the time, or only with selected kind of songs, ...)

**Comment by pescepalla** [comment] 2023-02-07 09:16
It happens consistently even after cleaning app data.

**Comment by soncaokim** [comment] 2023-02-07 10:15
Should be linked to this https://github.com/VinylMusicPlayer/VinylMusicPlayer/pull/666, which will be released in the upcoming version

**Closed by soncaokim** 2023-02-07 10:15 UTC
Labels: bug
