### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by vulgo** [VinylMusicPlayer/VinylMusicPlayer#899] opened 2023-12-23 15:00 UTC
App version: 1.6.2
App version code: 188
Android build version: ad9c24
Android release version: 11
Android SDK version: 30
Android build ID: RPXS31.Q2-58-17-7-3
Device brand: motorola
Device manufacturer: motorola
Device name: guamp
Device model: moto g(9) play
Device product name: guamp_retailen
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

## Time: 
2023/12/23 14:39:03
## Stack: 
java.io.FileNotFoundException: /storage/9016-4EF8/Music/Container/Gerald Donald/Virtual Geisha/folder.jpg: open failed: EACCES (Permission denied)
	at libcore.io.IoBridge.open(IoBridge.java:492)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at com.poupa.vinylmusicplayer.glide.audiocover.AbsCoverFetcher.fallback(SourceFile:1)
	at com.poupa.vinylmusicplayer.glide.audiocover.AbsCoverFetcher.fallback(SourceFile:2)
	at com.poupa.vinylmusicplayer.glide.audiocover.SongCoverFetcher.loadData(Unknown Source:65)
	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(Unknown Source:15)
	at com.bumptech.glide.load.engine.SourceGenerator.startNext(Unknown Source:97)
	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(Unknown Source:23)
	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(Unknown Source:59)
	at com.bumptech.glide.load.engine.DecodeJob.run(Unknown Source:29)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(Unknown Source:31)
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7733)
	at libcore.io.IoBridge.open(IoBridge.java:478)
	... 13 more

**Comment by soncaokim** [comment] 2023-12-24 08:11
Duplicate of #816

**Closed by soncaokim** 2023-12-24 08:11 UTC
Labels: bug
