### ISSUE TITLE
Lost cover and error message

### ISSUE THREAD

**Issue by Ennoia11** [VinylMusicPlayer/VinylMusicPlayer#817] opened 2023-10-18 13:49 UTC
**Describe the bug**
Almost all album covers aren't shown anymore + error message is shown

**To reproduce**
Play music

**Expected behavior**
Not showing an error message ans display album cover

**Device info**
App version: 1.5.3
App version code: 182
Android build version: 1695396170
Android release version: 13
Android SDK version: 33
Android build ID: TQ3C.230901.001.B1
Device brand: POCO
Device manufacturer: Xiaomi
Device name: munch
Device model: 22021211RG
Device product name: spark_munch
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
MicroG

**Additional context**
Dev options ans USB debug activate
I've got a pop-up dispaying this message :
org.jaudiotagger.audio.exceptions.CannotReadException: No Reader associated with this extension:opus
	at org.jaudiotagger.audio.AudioFileIO.readFile(Unknown Source:36)
	at org.jaudiotagger.audio.AudioFileIO.read(Unknown Source:4)
	at com.poupa.vinylmusicplayer.util.SAFUtil.loadAudioFile(Unknown Source:69)
	at com.poupa.vinylmusicplayer.glide.audiocover.AudioFileCoverFetcher.loadData(Unknown Source:10)
	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(Unknown Source:15)
	at com.bumptech.glide.load.engine.SourceGenerator.startNext(Unknown Source:97)
	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(Unknown Source:23)
	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(Unknown Source:59)
	at com.bumptech.glide.load.engine.DecodeJob.run(Unknown Source:29)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(Unknown Source:31)

**Comment by soncaokim** [comment] 2023-10-19 13:40
Should be a duplicate of https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/800 and possibly https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/816

**Closed by soncaokim** 2023-10-19 13:40 UTC
Labels: bug
