### ISSUE TITLE
Last played song is displayed as current song in widget

### ISSUE THREAD

**Issue by tschlegeldigos** [VinylMusicPlayer/VinylMusicPlayer#815] opened 2023-10-17 09:32 UTC
**Describe the bug**

This bug was present in older versions of Vinyl and seems to have been reintroduced. If more than one song is played, the song in the mini widget is one song behind the current playback.

**To reproduce**
1. Add some songs to the current playlist and start it
2. Upon automatic continuation of the songs the widget is updated incorrectly, displaying the previous played song

**Expected behavior**
The current playing song should be displayed in the widget.

**Device info**

 - Device: Samsung Galaxy A52s
 - Android Version: 13
 - Vinyl Music Player Version: 1.5.3

**Comment by NekoNoor** [comment] 2023-12-19 12:24
i noticed this is true for my now playing notification as well

**Comment by LizuROk** [comment] 2024-02-02 16:19
This also occurs on my phone too. Running galaxy s23 ultra with oneui 6.
However I am not sure if this is exclusive to Vinyl only. Vanilla has this issue too, even Metro at times.
Somehow samsung music is flawless. Could be a ONEUI issue?

**Comment by soncaokim** [comment] 2024-02-22 07:50
Close as duplicate of #631

**Closed by soncaokim** 2024-02-22 07:50 UTC
Labels: bug
