### ISSUE TITLE
Crash when selecting album

### ISSUE THREAD

**Issue by ovi-vansid** [VinylMusicPlayer/VinylMusicPlayer#938] opened 2024-02-03 20:49 UTC
**Describe the bug**

When selecting an album from the album view, a crash occurs. The device is running GrapheneOS and Storage Scopes are used to provide permissions. Songs can be accessed and played normally from the Songs view.

**To reproduce**
1. Start app
2. Tap on on 'Albums'
3. Scroll down to any album cover
4. Select/tap on album cover
5. Crash

**Expected behavior**
A listing of songs on the selected album should appear.

**Device info**
Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

App version: 1.7.0
App version code: 190
Android build version: 2024011600
Android release version: 14
Android SDK version: 34
Android build ID: UQ1A.240105.004.2024011600
Device brand: google
Device manufacturer: Google
Device name: lynx
Device model: Pixel 7a
Device product name: lynx
Device hardware name: lynx
ABIs: [arm64-v8a]
ABIs (32bit): []
ABIs (64bit): [arm64-v8a]

## Time: 
2024/02/03 15:38:15
## Stack: 
java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=100, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.poupa.vinylmusicplayer/com.poupa.vinylmusicplayer.ui.activities.AlbumDetailActivity}: java.lang.IllegalArgumentException: No suitable parent found from the given view. Please provide a valid view.
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5594)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5633)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2475)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.IllegalArgumentException: No suitable parent found from the given view. Please provide a valid view.
	at com.google.android.material.snackbar.Snackbar.makeInternal(Unknown Source:50)
	at com.google.android.material.snackbar.Snackbar.make(SourceFile:3)
	at com.poupa.vinylmusicplayer.ui.activities.base.AbsBaseActivity.onRequestPermissionsResult(Unknown Source:59)
	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:9168)
	at android.app.Activity.dispatchActivityResult(Activity.java:9026)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5587)
	... 15 more

**Comment by soncaokim** [comment] 2024-04-04 13:45
Duplicate of #908

**Closed by soncaokim** 2024-04-04 13:45 UTC
Labels: bug
