### ISSUE TITLE
Adaptive icon for Android 13 and later

### ISSUE THREAD

**Issue by UjuiUjuMandan** [VinylMusicPlayer/VinylMusicPlayer#883] opened 2023-12-08 12:15 UTC
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Draw the icon according to the docs.

**Describe alternatives you've considered**
None.

**Additional context**
See https://developer.android.com/develop/ui/views/launch/icon_design_adaptive .

**Comment by soncaokim** [comment] 2024-01-24 15:50
Duplicate of #635

**Closed by soncaokim** 2024-01-24 15:50 UTC
Labels: feature request
