### ISSUE TITLE
Crash when using a widget

### ISSUE THREAD

**Issue by tal33** [VinylMusicPlayer/VinylMusicPlayer#805] opened 2023-10-14 09:28 UTC
**Describe the bug**
Vinyl crashes after update when launching from any of its widgets.
Widget is also blank, no content displayed

**To reproduce**
1. Add Vinyl Widget to your launcher (i use Square Home2)
2. Click on Widget

**Expected behavior**
Works as in previous version. 

**Device info**
App version: 1.5.3
App version code: 182
Android build version: S918BXXS3AWHR
Android release version: 13
Android SDK version: 33
Android build ID: TP1A.220624.014.S918BXXS3AWHR
Device brand: samsung
Device manufacturer: samsung
Device name: dm3q
Device model: SM-S918B
Device product name: dm3qxeea
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

Time: Sat Oct 14 11:18:46 GMT+02:00 2023

Stack:
java.lang.IllegalArgumentException: com.poupa.vinylmusicplayer: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:408)
	at android.app.PendingIntent.buildServicePendingIntent(PendingIntent.java:767)
	at android.app.PendingIntent.getForegroundService(PendingIntent.java:759)
	at androidx.core.view.accessibility.a.e(Unknown Source:1)
	at com.poupa.vinylmusicplayer.appwidgets.base.BaseAppWidget.buildPendingIntent(Unknown Source:14)
	at com.poupa.vinylmusicplayer.appwidgets.base.BaseAppWidget.linkButtons(Unknown Source:42)
	at com.poupa.vinylmusicplayer.appwidgets.AppWidgetCard.performUpdate(Unknown Source:21)
	at com.poupa.vinylmusicplayer.appwidgets.base.BaseAppWidget.notifyChange(Unknown Source:23)
	at com.poupa.vinylmusicplayer.service.MusicService.sendChangeInternal(Unknown Source:25)
	at com.poupa.vinylmusicplayer.service.MusicService.handleAndSendChangeInternal(Unknown Source:3)
	at com.poupa.vinylmusicplayer.service.MusicService.notifyChange(Unknown Source:0)
	at com.poupa.vinylmusicplayer.service.ThrottledSeekHandler.run(Unknown Source:9)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by soncaokim** [comment] 2023-10-14 10:00
Duplicate of https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/789

**Closed by soncaokim** 2023-10-14 10:00 UTC
Labels: bug
