### ISSUE TITLE
Cannot read exception 

### ISSUE THREAD

**Issue by cmburg** [VinylMusicPlayer/VinylMusicPlayer#800] opened 2023-10-13 18:58 UTC
**Describe the bug**
org.jaudiotagger.audio.exceptions.CannotReadException: No Reader associated with this extension:opus
	at org.jaudiotagger.audio.AudioFileIO.readFile(Unknown Source:36)
	at org.jaudiotagger.audio.AudioFileIO.read(Unknown Source:4)
	at com.poupa.vinylmusicplayer.util.SAFUtil.loadAudioFile(Unknown Source:69)
	at com.poupa.vinylmusicplayer.util.MusicUtil.getLyrics(Unknown Source:12)
	at com.poupa.vinylmusicplayer.ui.fragments.player.card.CardPlayerFragment$3.doInBackground(Unknown Source:8)
	at com.poupa.vinylmusicplayer.ui.fragments.player.card.CardPlayerFragment$3.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

**To reproduce**
Refresh database. 

**Expected behavior**
Enlist songs as in previous versions 

**Device info**
Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

 - Device: xiaomi mi8
 - Android Version: 13
 - ROM:LOS 20-20231005-NIGHTLY-dipper 
 - Vinyl Music Player Version: 1.5.3

**Additional context**
It seems like it does not enlist "faulty" songs. When I browse to a missing song via android directory manager the song can be played. I'm not sure if it just happens on songs downloaded via newpipe. Song info might be useful:

Dateipfad: /storage/emulated/0/Music/NewPipe/Dimitri Vegas & Like Mike - Live At Tomorrowland 2023 Mainstage (FULL SET 4K UHD).m4a
Größe: 73,51 MB
Format: Aac
Bitrate: 0 kb/s
Abtastrate: 44100 Hz
Added: Sun Oct 08 13:46:04 GMT+02:00 2023
Modified: Sun Oct 08 13:46:16 GMT+02:00 2023
Titelnummer: 0
CD-Nummer: 0
Titel: Dimitri Vegas & Like Mike - Live At Tomorrowland 2023 Mainstage (FULL SET 4K UHD)
Interpret: 
Album: NewPipe
Album-Interpret: 
Genre: 
Jahr: -
Länge: 1:19:25
ReplayGain: - -

**Comment by cmburg** [comment] 2023-10-13 19:01
Well, I might have mixed two different error messages sindlce the aforementioned regards opus which had no issues in the past (or at least I was not aware of it). An other error message I get is

java.lang.NullPointerException: Attempt to invoke virtual method 'org.jaudiotagger.audio.AudioFile com.poupa.vinylmusicplayer.util.AutoDeleteAudioFile.get()' on a null object reference
	at com.poupa.vinylmusicplayer.util.MusicUtil.getLyrics(Unknown Source:16)
	at com.poupa.vinylmusicplayer.ui.fragments.player.card.CardPlayerFragment$3.doInBackground(Unknown Source:8)
	at com.poupa.vinylmusicplayer.ui.fragments.player.card.CardPlayerFragment$3.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by soncaokim** [comment] 2023-10-13 22:23
SHould be a duplicate of https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/794

**Closed by soncaokim** 2023-10-13 22:23 UTC
Labels: bug
