### ISSUE TITLE
Android 12/ Title Freeze 

### ISSUE THREAD

**Issue by IAlwayWasALoser** [VinylMusicPlayer/VinylMusicPlayer#719] opened 2023-03-08 01:29 UTC
**Describe the bug**
Title of the song on the pin notification area freeze when it move the new song.
**Device info**
 - Device: Redmi Note 11s
 - Android Version:12
 - ROM: 13.0.7 SKEMIXM
 - Vinyl Music Player Version: 
1.5..0

**Comment by soncaokim** [comment] 2023-07-08 13:52
Closing this, duplicate of #732

**Closed by soncaokim** 2023-07-08 13:52 UTC
Labels: bug
