### ISSUE TITLE
Crashed while attempting to save a tag edit, including a cover download

### ISSUE THREAD

**Issue by jkpirie** [VinylMusicPlayer/VinylMusicPlayer#976] opened 2024-03-07 14:13 UTC
**Describe the bug*
App crashes while trying to save a tag edit including a cover download. All is well until save is clicked.

**To reproduce**
1. Go to 'tag editor
2. Click on save following edit
3. 
4. App crashes with error dialogue

Expected behaviour:
App saves the tav edit including a downloaded cover

**Device info**

Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

 - Device: Fairphone 4
 - Android Version: 12
 - ROM: e/OS
 - Vinyl Music Player Version: 1.8.0

**Additional context**

**Comment by soncaokim** [comment] 2024-03-20 16:16
Hi, what was the track format involved? i.e. MP3/AAC/FLAC/...?

**Comment by soncaokim** [comment] 2024-04-01 12:04
I'm closing this issue since it lacks information to reproduce. Please dont hesitate to reopen with more info

**Closed by soncaokim** 2024-04-01 12:04 UTC
Labels: bug, can't reproduce
