### ISSUE TITLE
1.5.3: "Invalid Identification header for this Ogg File", but file plays fine

### ISSUE THREAD

**Issue by mihawk90** [VinylMusicPlayer/VinylMusicPlayer#804] opened 2023-10-14 00:30 UTC
**Describe the bug**
After the update, Vinyl keeps spitting out this error every time I play my files and it seems to do that on a regular basis.

**To reproduce**
1. Get some Ogg/Opus files (i.e. Opus with `.ogg` extension) including cover art
2. Play file
3. Error is in my case going straight to clipboard (Android is giving me a notification for changes in the clipboard).

**Expected behavior**
Not seeing an error as it worked perfectly fine in previous versions.

**Device info**
App version: 1.5.3
App version code: 182
Android build version: gms-88126537
Android release version: 13
Android SDK version: 33
Android build ID: 6.A.020.0
Device brand: Fairphone
Device manufacturer: Fairphone
Device name: FP3
Device model: FP3
Device product name: FP3
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

**Additional context**
```
org.jaudiotagger.audio.exceptions.CannotReadException: Invalid Identification header for this Ogg File
	at org.jaudiotagger.audio.ogg.util.OggInfoReader.read(Unknown Source:381)
	at org.jaudiotagger.audio.ogg.OggFileReader.getEncodingInfo(Unknown Source:2)
	at org.jaudiotagger.audio.generic.AudioFileReader.read(Unknown Source:129)
	at org.jaudiotagger.audio.AudioFileIO.readFile(Unknown Source:14)
	at org.jaudiotagger.audio.AudioFileIO.read(Unknown Source:4)
	at com.poupa.vinylmusicplayer.util.SAFUtil.loadAudioFile(Unknown Source:69)
	at com.poupa.vinylmusicplayer.glide.audiocover.AudioFileCoverFetcher.loadData(Unknown Source:10)
	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(Unknown Source:15)
	at com.bumptech.glide.load.engine.SourceGenerator.startNext(Unknown Source:97)
	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(Unknown Source:23)
	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(Unknown Source:59)
	at com.bumptech.glide.load.engine.DecodeJob.run(Unknown Source:29)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(Unknown Source:31)
```

I'll get the ffprobe output when I'm back on my PC.

Files were downloaded using youtube-dl and handled through ffmpeg. Tagged using Mp3tag through WINE.

**Comment by soncaokim** [comment] 2023-10-14 09:58
Duplicate of https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/800

**Closed by soncaokim** 2023-10-14 09:58 UTC
Labels: bug
