### ISSUE TITLE
Crash after update on 1.6.1

### ISSUE THREAD

**Issue by pfsenseuser** [VinylMusicPlayer/VinylMusicPlayer#876] opened 2023-12-02 12:47 UTC
**Describe the bug**
Crash when closing app.
**Device info**
Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

 - Device: redmi note 11 pro
 - Android Version:13
 - ROM:
 - Vinyl Music Player Version:1.6.1

**Comment by soncaokim** [comment] 2023-12-08 14:04
I'm closing this due to lack of actionable info (stack trace) and not reproducible.
Please dont hesitate to reopen with more info.

**Closed as not planned by soncaokim** 2023-12-08 14:04 UTC
Labels: bug
