### ISSUE TITLE
TopAndRecentlyPlayed: The application constantly crashes due to corrupt DB

### ISSUE THREAD

**Issue by vova7878** [VinylMusicPlayer/VinylMusicPlayer#975] opened 2024-03-07 10:50 UTC
**Describe the bug**
 At a certain point vinyl began to crash on startup, rebooting the phone did not help

**Device info**
App version: 1.8.0
App version code: 191
Android build version: eng.blacks.20200101.151935
Android release version: 9
Android SDK version: 28
Android build ID: PQ3A.190801.002
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: nitrogen
Device model: MI MAX 3
Device product name: nitrogen
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

## Time: 
2024/03/07 17:46:35
## Stack: 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:354)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalStateException: Couldn't read row 1052, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:538)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
	at com.poupa.vinylmusicplayer.provider.SongPlayCountStore.updateExistingRow(Unknown Source:6)
	at com.poupa.vinylmusicplayer.provider.SongPlayCountStore.updateResults(Unknown Source:56)
	at com.poupa.vinylmusicplayer.provider.SongPlayCountStore.<init>(Unknown Source:18)
	at com.poupa.vinylmusicplayer.provider.SongPlayCountStore.getInstance(Unknown Source:13)
	at com.poupa.vinylmusicplayer.loader.TopAndRecentlyPlayedTracksLoader.getTopTracks(Unknown Source:16)
	at com.poupa.vinylmusicplayer.model.smartplaylist.MyTopTracksPlaylist.getSongs(Unknown Source:0)
	at com.poupa.vinylmusicplayer.model.Playlist.getInfoString(Unknown Source:0)
	at com.poupa.vinylmusicplayer.adapter.PlaylistAdapter$1.doInBackground(SourceFile:2)
	at com.poupa.vinylmusicplayer.adapter.PlaylistAdapter$1.doInBackground(SourceFile:1)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

**Comment by vova7878** [comment] 2024-03-07 10:55
I updated the player, the behavior did not change

App version: 1.8.1
App version code: 192
Android build version: eng.blacks.20200101.151935
Android release version: 9
Android SDK version: 28
Android build ID: PQ3A.190801.002
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: nitrogen
Device model: MI MAX 3
Device product name: nitrogen
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

## Time: 
2024/03/07 17:54:11
## Stack: 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:354)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalStateException: Couldn't read row 1052, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:538)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
	at com.poupa.vinylmusicplayer.provider.SongPlayCountStore.updateExistingRow(Unknown Source:6)
	at com.poupa.vinylmusicplayer.provider.SongPlayCountStore.updateResults(Unknown Source:56)
	at com.poupa.vinylmusicplayer.provider.SongPlayCountStore.<init>(Unknown Source:18)
	at com.poupa.vinylmusicplayer.provider.SongPlayCountStore.getInstance(Unknown Source:13)
	at com.poupa.vinylmusicplayer.loader.TopAndRecentlyPlayedTracksLoader.getTopTracks(Unknown Source:16)
	at com.poupa.vinylmusicplayer.model.smartplaylist.MyTopTracksPlaylist.getSongs(SourceFile:1)
	at com.poupa.vinylmusicplayer.model.smartplaylist.MyTopTracksPlaylist.getSongs(SourceFile:2)
	at com.poupa.vinylmusicplayer.model.Playlist.getInfoString(Unknown Source:0)
	at com.poupa.vinylmusicplayer.adapter.PlaylistAdapter$1.doInBackground(SourceFile:2)
	at com.poupa.vinylmusicplayer.adapter.PlaylistAdapter$1.doInBackground(SourceFile:1)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

**Comment by soncaokim** [comment] 2024-03-07 10:57
Sorry to hear that. Seems like the DB is corrupt.

To workaround, can you clear the app data (or uninstall then reinstall it). You will lose the settings and play history unfortunately.

**Comment by vova7878** [comment] 2024-03-07 12:38
OK, it helped. But how to avoid such damage in the future? Can you ask the user to clean up the database if it becomes corrupted?

**Comment by soncaokim** [comment] 2024-03-20 16:08
To me the DB should not be corrupt in the first place. Doing a cleanup would only evade the root cause which remains unknown to me.

Since you have a mean to manually clean it, and I suppose this is not happening frequently, I'm closing the issue for now.

If I have more information, I will investigate.

**Closed by soncaokim** 2024-03-20 16:08 UTC
Labels: bug

**Comment by soncaokim** [comment] 2024-03-20 16:11
In the case the issue happens again, I will modify the behaviour not to crash repeatedly and render the app unusable.
