### ISSUE TITLE
Vinyl Music Player crashed + is slower

### ISSUE THREAD

**Issue by LalOpen** [VinylMusicPlayer/VinylMusicPlayer#852] opened 2023-11-12 13:32 UTC
App version: 1.5.6
App version code: 185
Android build version: L751_10.22.2
Android release version: 12
Android SDK version: 31
Android build ID: SKQ1.220303.001 release-keys
Device brand: Crosscall
Device manufacturer: Crosscall
Device name: L751
Device model: Core-M5
Device product name: L751
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

Time: Sun Nov 12 14:28:08 GMT+01:00 2023

Stack:
java.lang.IllegalArgumentException: Volume external_primary not found
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:481)
	at android.content.ContentResolver.query(ContentResolver.java:1223)
	at android.content.ContentResolver.query(ContentResolver.java:1154)
	at android.content.ContentResolver.query(ContentResolver.java:1110)
	at com.poupa.vinylmusicplayer.loader.PlaylistLoader.getAllPlaylists(Unknown Source:23)
	at com.poupa.vinylmusicplayer.provider.StaticPlaylist.importDevicePlaylists(Unknown Source:41)
	at com.poupa.vinylmusicplayer.provider.StaticPlaylist.getAllPlaylists(Unknown Source:50)
	at com.poupa.vinylmusicplayer.provider.StaticPlaylist.getPlaylist(Unknown Source:0)
	at com.poupa.vinylmusicplayer.util.MusicUtil.getFavoritesPlaylist(Unknown Source:7)
	at com.poupa.vinylmusicplayer.util.MusicUtil.isFavorite(Unknown Source:0)
	at com.poupa.vinylmusicplayer.service.notification.PlayingNotificationImplApi24.update(Unknown Source:18)
	at com.poupa.vinylmusicplayer.service.MusicService.updateNotification(Unknown Source:21)
	at com.poupa.vinylmusicplayer.service.MusicService.handleChangeInternal(Unknown Source:152)
	at com.poupa.vinylmusicplayer.service.MusicService.handleAndSendChangeInternal(Unknown Source:0)
	at com.poupa.vinylmusicplayer.service.MusicService.notifyChange(Unknown Source:0)
	at com.poupa.vinylmusicplayer.service.ThrottledSeekHandler.run(Unknown Source:9)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)

Plus : since a recent update, Vinyl Music Player forget at every wake up the cover of all my albums and is therefore much more slow...

**Comment by kuweonhub** [comment] 2023-11-18 12:31
Dear commiters,
I strongly support the "is slower"/ nearly unusable claim.

Since installation of 1.5.6 from F-Droid I have vast problems using Vinyl.

**To reproduce**
 * not reproducable
 * occures occationally but often

**bug decription**
 * after opening Vinyl:
   * Phone freezes
   * all functions (eg. play, timer) take several seconds to respond

**Device info**
 * Device: Nokia 6
 * Android Version: 9
 * Vinyl Music Player Version: 1.5.6

**Additional context**
 * Maybe the issue is related to #853
 * I noticed directly after the update to 1.5.6 that in the "app-Info/storage" the application claimed several GB of space. When I entered the storage details and -without activating any actions- left it again, the storage decreased to a reasonable much lower amount.
 * I already re-installed 1.5.6 from F-Droid. No changes here.

Thanks
Kai

**Comment by soncaokim** [comment] 2023-11-25 16:23
Closing this since the "slower"part should be addressed by #812

**Closed by soncaokim** 2023-11-25 16:23 UTC
Labels: bug
