### ISSUE TITLE
The app crashes upon startup

### ISSUE THREAD

**Issue by vojtech2** [VinylMusicPlayer/VinylMusicPlayer#803] opened 2023-10-13 19:43 UTC
**Describe the bug**

The app crashes upon startup. It started happening after update to 1.5.3. Before the update it would crash the whole Android screen and cause it to restart and then stay in a restart-crash loop so that the only way to come out was to restart my phone. Now only the app crashes and shows a dialog to submit the crash report.

**To reproduce**

Simply open the app. The app crashes immediately after starting it.

**Expected behavior**

The app doesn't crash upon startup.

**Device info**

App version: 1.5.3
App version code: 182
Android build version: c6541019ac
Android release version: 12
Android SDK version: 32
Android build ID: lineage_sargo-userdebug 12 SQ3A.220705.004 c6541019ac
Device brand: google
Device manufacturer: Google
Device name: sargo
Device model: Pixel 3a
Device product name: sargo
Device hardware name: sargo
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

Time: Fri Oct 13 20:31:11 GMT+01:00 2023

Stack:
java.lang.IllegalArgumentException: com.poupa.vinylmusicplayer: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
	at android.app.PendingIntent.buildServicePendingIntent(PendingIntent.java:724)
	at android.app.PendingIntent.getForegroundService(PendingIntent.java:716)
	at androidx.core.view.accessibility.a.e(Unknown Source:1)
	at com.poupa.vinylmusicplayer.appwidgets.base.BaseAppWidget.buildPendingIntent(Unknown Source:14)
	at com.poupa.vinylmusicplayer.appwidgets.base.BaseAppWidget.linkButtons(Unknown Source:42)
	at com.poupa.vinylmusicplayer.appwidgets.AppWidgetClassic.performUpdate(Unknown Source:18)
	at com.poupa.vinylmusicplayer.appwidgets.base.BaseAppWidget.notifyChange(Unknown Source:23)
	at com.poupa.vinylmusicplayer.service.MusicService.sendChangeInternal(Unknown Source:15)
	at com.poupa.vinylmusicplayer.service.MusicService.handleAndSendChangeInternal(Unknown Source:3)
	at com.poupa.vinylmusicplayer.service.MusicService.notifyChange(Unknown Source:0)
	at com.poupa.vinylmusicplayer.service.ThrottledSeekHandler.run(Unknown Source:9)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by vojtech2** [comment] 2023-10-13 20:04
Issue gone after I removed my Vinyl widget. However I'm now back to Android screen crash and restart-crash loop.

**Comment by soncaokim** [comment] 2023-10-13 22:21
This should be a duplicate of https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/789

**Closed by soncaokim** 2023-10-13 22:21 UTC
Labels: bug
