### ISSUE TITLE
Crashing,unusable 

### ISSUE THREAD

**Issue by chillgamesh** [VinylMusicPlayer/VinylMusicPlayer#814] opened 2023-10-16 02:28 UTC
Crashes every time I open the app, home screen widget is not appearing either. Tried to downgrade through fdroid store as an interim solution, but got an unknown error message every time. Crash data is as follows: 

App version: 1.5.3
App version code: 182
Android build version: A326USQUBDWI8
Android release version: 13
Android SDK version: 33
Android build ID: TP1A.220624.014.A326USQUBDWI8
Device brand: samsung
Device manufacturer: samsung
Device name: a32x
Device model: SM-A326U
Device product name: a32xsq
Device hardware name: mt6853
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

Time: Sun Oct 15 22:24:27 EDT 2023

Stack:
java.lang.IllegalArgumentException: com.poupa.vinylmusicplayer: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:408)
	at android.app.PendingIntent.buildServicePendingIntent(PendingIntent.java:767)
	at android.app.PendingIntent.getForegroundService(PendingIntent.java:759)
	at androidx.core.view.accessibility.a.e(Unknown Source:1)
	at com.poupa.vinylmusicplayer.appwidgets.base.BaseAppWidget.buildPendingIntent(Unknown Source:14)
	at com.poupa.vinylmusicplayer.appwidgets.base.BaseAppWidget.linkButtons(Unknown Source:42)
	at com.poupa.vinylmusicplayer.appwidgets.AppWidgetClassic.performUpdate(Unknown Source:18)
	at com.poupa.vinylmusicplayer.appwidgets.base.BaseAppWidget.notifyChange(Unknown Source:23)
	at com.poupa.vinylmusicplayer.service.MusicService.sendChangeInternal(Unknown Source:15)
	at com.poupa.vinylmusicplayer.service.MusicService.handleAndSendChangeInternal(Unknown Source:3)
	at com.poupa.vinylmusicplayer.service.MusicService.notifyChange(Unknown Source:0)
	at com.poupa.vinylmusicplayer.service.ThrottledSeekHandler.run(Unknown Source:9)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by SuzaBr** [comment] 2023-10-18 16:13
Hi,
experienced the same, App always crashing. Happy, there is a fix!
@chillgamesh Downgrade should only be possible after you uinstalled the app, as mentioned before.

However, with Vinyl I experience Crashes after Updates way more often than with other apps.

Maybe it is time to do something about this?
Like regression tests, more beta testers, etc.?

**Comment by soncaokim** [comment] 2023-10-21 09:04
Duplicate of #789

**Closed by soncaokim** 2023-10-21 09:04 UTC
Labels: bug

**Comment by erebion** [comment] 2023-10-21 11:30
Are you sure? This is a crash report for crashes every time the app is opened, the other one is for crashes when playing music. 🤔
