### ISSUE TITLE
Crash on app open

### ISSUE THREAD

**Issue by ebm539** [VinylMusicPlayer/VinylMusicPlayer#819] opened 2023-10-19 12:40 UTC
Crashes when opening the app.

App version: 1.5.4
App version code: 183
Android build version: 623594567
Android release version: 8.0.0
Android SDK version: 26
Android build ID: 47.1.A.16.20
Device brand: Sony
Device manufacturer: Sony
Device name: G8341
Device model: G8341
Device product name: G8341
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

Time: Fri Oct 20 01:38:37 GMT+13:00 2023

Stack:
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:353)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
	at android.os.Handler.<init>(Handler.java:203)
	at android.os.Handler.<init>(Handler.java:117)
	at android.content.ClipboardManager$2.<init>(ClipboardManager.java:62)
	at android.content.ClipboardManager.<init>(ClipboardManager.java:62)
	at android.app.SystemServiceRegistry$11.createService(SystemServiceRegistry.java:257)
	at android.app.SystemServiceRegistry$11.createService(SystemServiceRegistry.java:255)
	at android.app.SystemServiceRegistry$CachedServiceFetcher.getService(SystemServiceRegistry.java:954)
	at android.app.SystemServiceRegistry.getSystemService(SystemServiceRegistry.java:906)
	at android.app.ContextImpl.getSystemService(ContextImpl.java:1651)
	at androidx.appcompat.view.ContextThemeWrapper.getSystemService(Unknown Source:33)
	at android.view.ContextThemeWrapper.getSystemService(ContextThemeWrapper.java:171)
	at android.app.Activity.getSystemService(Activity.java:5893)
	at com.poupa.vinylmusicplayer.util.OopsHandler.copyStackTraceToClipboard(Unknown Source:2)
	at com.poupa.vinylmusicplayer.util.MusicUtil.getLyrics(Unknown Source:51)
	at com.poupa.vinylmusicplayer.ui.fragments.player.card.CardPlayerFragment$3.doInBackground(Unknown Source:12)
	at com.poupa.vinylmusicplayer.ui.fragments.player.card.CardPlayerFragment$3.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

**Comment by soncaokim** [comment] 2023-10-19 13:14
Duplicate of #802. This will be fixed in the next release

**Closed by soncaokim** 2023-10-19 13:14 UTC
Labels: bug
