### ISSUE TITLE
Crash on marking / unmarking as favourite

### ISSUE THREAD

**Issue by tschlegeldigos** [VinylMusicPlayer/VinylMusicPlayer#702] opened 2023-02-22 09:07 UTC
**Describe the bug**
Marking and afterwards unmarking a song as favourite reproducibly crashes the app. I used this to work around the song not being updated (see also #627 and #631), but since one or two Vinyl updates this leads to crashes.

**To reproduce**
1. Open the app
2. Start any song
3. Mark it as favourite by tapping on the heart, either on the main screen or in the notification area
4. Unmark it
5. The app crashes. Sometimes it just returns to the main screen, sometimes it is minimized to the background, sometimes it crashes completely and Android complains about frequent crashes of the app.

**Expected behavior**
No crash on changing the favourite status.

**Device info**
Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

 - Device: Samsung A52s
 - Android Version: 13
 - Vinyl Music Player Version: 1.4.1 (via F-Droid)

**Comment by soncaokim** [comment] 2023-02-22 09:52
hello, this is a known bug (my fault) and is fixed in the version 1.5.0.
Duplicate of https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/674

**Closed by soncaokim** 2023-02-22 09:52 UTC
Labels: bug

**Comment by tschlegeldigos** [comment] 2023-02-22 09:55
Ah, I didn't see this, I only looked through the open issues.

Thanks, I'm looking forward to the version upgrade :+1:
