### ISSUE TITLE
Song title not changing after previous song ended

### ISSUE THREAD

**Issue by k3rnelPan1c228** [VinylMusicPlayer/VinylMusicPlayer#631] opened 2022-12-11 13:52 UTC
**Bug**
Song title name not changing after previous song ended and it shows as its  paused in previous song

**To Reproduce**
1. Play some song
2. Let it finish playing or skip to next song
3. See the notification panel
(I also turned on and off "Classic Notification Design a few times in between)

**Screenshots**
What's playing:
![Screenshot_20221211-191737_Vinyl Music Player.png](https://user-images.githubusercontent.com/115926645/206907500-24c84d83-1990-4f15-8113-a8c60765536f.png)
Whats Shown:
![Screenshot_20221211-191730_Vinyl Music Player.png](https://user-images.githubusercontent.com/115926645/206907535-b37526dc-ad0e-418c-867a-f686302c8bd0.png)

**Smartphone:**
 - Device: Samsung A31
 - Android Version: 12
 - Vinyl Music Player Version: 1.3.0 (latest)

**Comment by Tau5** [comment] 2023-02-05 12:03
Can reproduce

**Comment by yashpalgoyal1304** [comment] 2023-02-09 16:41
Hey @k3rnelPan1c228 can u please replace the image as suggested below, as it is toooo long and makes it inconvenient to browse the issue:

currently, it should be something like this:
```
![<name>](<link>)
```

convert it to:
```
<img src="<link>" width=450px/>
```

thanks!

**Comment by yashpalgoyal1304** [comment] 2023-02-09 16:50
I came here to file issue _almost_ similar to this.

_Almost_ as the steps are not exactly same, u actually have to let the song play for quite some time. Just mere 5-10 seconds don't cause the issue. That's why i think it has to do something with battery optimisations or such.

- Reproduced with above comments with VinylMusicPlayer v1.4.1 (via f-droid) on Android 12 
- Not reproduced on [Maxfour Music Player] v1.3.4 (an older, yet another app based on phonograph)

[Maxfour Music Player]: https://github.com/MaxFour/Music-Player

**Comment by soncaokim** [comment] 2023-02-25 08:58
Is this still happening with the version 1.5.0?

Thanks

**Comment by yashpalgoyal1304** [comment] 2023-02-25 15:35
i am not able to reproduce this issue consistently in 1.4.1 itself (as i slightly hinted in above comment too)... so, can't say about v1.5.0

i will wait for some weeks before updating to see if i see this issue again in v1.4.1

**Comment by yashpalgoyal1304** [comment] 2023-02-25 15:57
oh, i guess i forgot to upload the screenrecord video. I just re-reproduced it consistently now. here's the screenrecord and steps

issue: the play/pause status becomes out of sync in notification panel

the only situations test with: power saver mode on, and turning off the screen  (aka locking the phone) using power button - turning on after _some minutes_


https://user-images.githubusercontent.com/19423063/221366542-35aed7cd-bfea-4a01-8b4c-1fa33186a3f2.mp4

**Comment by soncaokim** [comment] 2023-02-25 16:48
There was a similar issue in pre-1.5.0, should be fixed now. I'd be interested if you can confirm this.

Thanks for the report and screen recording.

**Comment by n2burns** [comment] 2023-07-27 13:52
I'm still experiencing this issue on version 1.5.2 from f-droid.

**Comment by goyalyashpal** [comment] 2023-08-14 13:45
> I'd be interested if you can confirm this.

just reproduced this "play" status not updated on 1.5.2

android 12; realme ui v3.0

<details><summary>screenrecord</summary>
<br/>**please enable sound**


https://github.com/VinylMusicPlayer/VinylMusicPlayer/assets/19423063/27cab3ca-97d8-47db-b699-719cb3968666



</details>

**Comment by jneidel** [comment] 2023-12-15 05:16
Still reproducible in 1.6.1

<img width=150 src="https://github.com/VinylMusicPlayer/VinylMusicPlayer/assets/25589715/f1893b69-b7cf-4635-abde-899ccea81280"/>
<img width=150 src="https://github.com/VinylMusicPlayer/VinylMusicPlayer/assets/25589715/b2841463-bace-4325-834d-8de7b62d43d8"/>

**Comment by tschlegeldigos** [comment] 2024-02-27 10:00
> Hi all,
> 
> I might have found a lead to fix this annoyance. I'd need some volunteer, who is able to reproduce the issue, and willing to install a development version of the app to check if the fix included is OK or not.
> 
> I cannot reproduce this bug consistently, unfortunately.
> 
> Related code change: #961

Hi @soncaokim , If you send me instructions on how to do this, I can try the development version.

**Comment by LizuROk** [comment] 2024-02-27 17:36
> Hi all,
> 
> I might have found a lead to fix this annoyance. I'd need some volunteer, who is able to reproduce the issue, and willing to install a development version of the app to check if the fix included is OK or not.
> 
> I cannot reproduce this bug consistently, unfortunately.
> 
> Related code change: #961

I am willing to test it too. Let me know when

**Comment by soncaokim** [comment] 2024-02-28 13:31
Thanks @tschlegeldigos  and @LizuROk for your offer.

Please proceed only if you are confortable with installing a software not from PlayStore, following instructions of a stranger on the Internet. This may require you to bypass some security measure on your device - by default downloaded software might not be allowed.

The development version can be downloaded from here: https://github.com/VinylMusicPlayer/VinylMusicPlayer/actions/runs/8051270045/artifacts/1275611438.

Please unzip and install the provided .apk file.

**Comment by soncaokim** [comment] 2024-02-28 14:06
Arf, bad news.

I'm still having this issue even with the mentioned change in place. Will keep an eye on this.

S.

**Comment by tschlegeldigos** [comment] 2024-02-28 14:12
I can confirm, but I have some additional info:

I removed my existing installation prior to installing the apk, including deletion of the cache and settings. (Device Info: Samsung Galaxy A52s, Android 14 / OneUI 6.0)

After I then installed from the apk and loaded the audio files, I observed the same behavior as before, the widget is always one song behind, after the first selected one finished.

But I also tinkered around with the settings and found out, that the issue doesn't happen with the "Classic Notification Design", at least the handful of tests I did were successful. In this case the displayed song is correct.

Maybe this helps narrowing down the problem.

**Comment by soncaokim** [comment] 2024-03-01 17:18
Hello,

I think I've found the culprit (a change attempted a while ago to improve the cover image quality). I've rolled back the change. 

The downside is that 
- the cover image on Android Oreo notification (that is built by the OS) is low-res, 
- and for those who use Android Auto, there is no hi-res cover image (not a regression)

Can you please help confirming this with this development version: https://github.com/VinylMusicPlayer/VinylMusicPlayer/actions/runs/8114720740/artifacts/1290008753

**Comment by tschlegeldigos** [comment] 2024-03-01 18:51
I tested this version and can confirm both, the song displayed is correct for both design variations, as well as the display of the cover in low-res, even if the cover should be something around 1000x1000 pixels.

Personally, I'd rather have the correct song in low-res on the widget, than the wrong on in hi-res, but maybe you can find a solution to satisfy both?

**Comment by LizuROk** [comment] 2024-03-01 18:54
I have tested the app and I can confirm that the classic notification is what fixes the issue.
Maybe something can be fixed with the current notification? Not sure how I can help.
Regardless, is it some sort of api issue? Metro music player and Auxio work good, especially on the "new" notification for music player.
I hope I was helpful. If you need my help further, let me know.

Mar 1, 2024 20:51:56 Thomas ***@***.***>:

**Comment by soncaokim** [comment] 2024-03-02 14:23
Hi testers, thanks for your feedbacks!

I've attempted a new fix, which would provide in addition a hi-res version of the cover art (if available). This would provide cover art to Android Auto and similar recipients as well (TV, watch, etc).

Can you please help checking that this is working for you, which ever the classic and normal notifications setting?
https://github.com/VinylMusicPlayer/VinylMusicPlayer/actions/runs/8123294446/artifacts/1291726018

--

Btw, do you still use the classic notification? I'm thinking of removing it, since it looks out of place with recent version of Androids.

**Comment by LizuROk** [comment] 2024-03-02 14:33
Hello!
The notification seems to be working fine now. I do suggest getting rid of the classic notification too.
I do however encountered a strange "bug". It no longer promps me to grant media permissions but rather sends me to the vinyl's app info section in settings. Not a big deal and nothing of importance.
Thank you!

Mar 2, 2024 16:23:15 soncaokim ***@***.***>:

**Comment by tschlegeldigos** [comment] 2024-03-04 07:58
> Hi testers, thanks for your feedbacks!
> 
> I've attempted a new fix, which would provide in addition a hi-res version of the cover art (if available). This would provide cover art to Android Auto and similar recipients as well (TV, watch, etc).
> 
> Can you please help checking that this is working for you, which ever the classic and normal notifications setting? https://github.com/VinylMusicPlayer/VinylMusicPlayer/actions/runs/8123294446/artifacts/1291726018

Works fine with both versions.

> 
> --
> 
> Btw, do you still use the classic notification? I'm thinking of removing it, since it looks out of place with recent version of Androids.

I only used it as a fallback while debugging now. Otherwise it's not integrating nicely, as you said, so I'm usually never using it.

**Closed** 2024-03-04 08:09 UTC
Labels: bug
