### ISSUE TITLE
Crash on Initial Library Scan

### ISSUE THREAD

**Issue by t0fr** [VinylMusicPlayer/VinylMusicPlayer#1062] opened 2024-04-29 23:30 UTC
**Describe the bug**
App crashes on initial library scan. Crash occurs multiple times on trying to complete it.

**To reproduce**
1. Freshly install v1.10.0 from Fdroid
2. Give access to files
3. Auto library scan starts
4. App crashes
5. Launch again
6. Scan resumes
7. App crashes

**Expected behavior**
App does not crash and completes scan the first time.

**Device info**

 - Device:  Pixel 6
 - Android Version: 14
 - ROM: Stock
 - Vinyl Music Player Version: 1.10.0 from Fdroid

**Additional context**
Here is the output from the crash report

App version: 1.10.0
App version code: 197
Android build version: 11480754
Android release version: 14
Android SDK version: 34
Android build ID: AP1A.240405.002
Device brand: google
Device manufacturer: Google
Device name: oriole
Device model: Pixel 6
Device product name: oriole
Device hardware name: oriole
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

## Time: 
2024/04/29 19:25:53
## Stack: 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Set java.util.Map.entrySet()' on a null object reference
	at com.poupa.vinylmusicplayer.discog.MemCache.removeSongById(Unknown Source:34)
	at com.poupa.vinylmusicplayer.discog.Discography.removeSongById(Unknown Source:16)
	at com.poupa.vinylmusicplayer.discog.Discography.syncWithMediaStore(Unknown Source:124)
	at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.doInBackground(SourceFile:1)
	at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.doInBackground(SourceFile:2)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 4 more

**Comment by soncaokim** [comment] 2024-05-10 10:41
Duplicate of #1039, #1044

**Closed by soncaokim** 2024-05-10 10:41 UTC
Labels: bug
