### ISSUE TITLE
Cant blacklist due to permissions

### ISSUE THREAD

**Issue by Kreuger** [VinylMusicPlayer/VinylMusicPlayer#826] opened 2023-10-22 18:40 UTC
**Describe the bug**
Hello. I recently tried to add a folder to my blacklist but the app says it doesnt have the permission "read media audio". When I go to the permissions setting

**To reproduce**
Open settings, tap blacklist, tap add

**Expected behavior**
Should be given dialogue to choose a folder or the app should ask for the required permission to be granted.

**Device info**
Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

 - Device: OnePlus Nord N10 5G
 - Android Version: 11
 - ROM: Stock, with root
 - Vinyl Music Player Version: 1.5.3
 
![Screenshot_20231022-143903](https://github.com/VinylMusicPlayer/VinylMusicPlayer/assets/42020/a4229929-f017-45a7-a5eb-6e62f8e89052)

![Screenshot_20231022-143958](https://github.com/VinylMusicPlayer/VinylMusicPlayer/assets/42020/5648b1dc-23a8-4357-b0cb-e57ec223be94)

**Comment by soncaokim** [comment] 2024-01-24 17:31
Duplicate of https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/916

**Closed by soncaokim** 2024-01-24 17:31 UTC
Labels: bug
