### ISSUE TITLE
Folder view dont show files with Cyrillic name

### ISSUE THREAD

**Issue by Myaukolka** [VinylMusicPlayer/VinylMusicPlayer#792] opened 2023-10-13 13:01 UTC
**Describe the bug**
Version 1.5.3 only displays Latin file names in folders view. Files with Cyrillic names are not visible, folder scan doesn't count them either. All files are still appearing under library view. Issue is not present on version 1.5.2.

**To reproduce**
1. Install version 1.5.3
2. Get an audio file with filename other that latin
3. Open folder with that file in Vinyl folder view
4. File is not visible

**Expected behavior**
All files should be visible

**Device info**
Samsung Galaxy S8+

 - Device: 
 - Android Version: 9
 - ROM: stock
 - Vinyl Music Player Version: 1.5.3 Play Store

**Additional context**
Library scan on version 1.5.2 is also several times faster than on 1.5.3

**Comment by soncaokim** [comment] 2023-10-13 13:05
If possible, can you please share a sample file that doesnt have Cyrillic properly handled? And please share the expected output.

**Comment by Myaukolka** [comment] 2023-10-13 13:15
**Storage app showing 2 audio files**
![photo_2023-10-13_15-11-02](https://github.com/VinylMusicPlayer/VinylMusicPlayer/assets/57365791/11cd3527-b582-4709-af06-6b5f614b60ea)

**Library view showing both files**
![photo_2023-10-13_15-11-01](https://github.com/VinylMusicPlayer/VinylMusicPlayer/assets/57365791/6735179d-e923-4f5f-97fe-c524aa62919a)

**Folder view only showing one file**
![photo_2023-10-13_15-11-01 (2)](https://github.com/VinylMusicPlayer/VinylMusicPlayer/assets/57365791/60e9bf6d-d358-4f65-b642-99b0e71d27fe)

Cyrillic audio file in zip archive: 
[audio.zip](https://github.com/VinylMusicPlayer/VinylMusicPlayer/files/12893852/audio.zip)

**Comment by soncaokim** [comment] 2023-10-13 16:02
Reproduced, will rename the bug report to reflect the issue more precisely

**Comment by soncaokim** [comment] 2023-10-13 16:46
Looks like there is a bug/regression in the underlying method we used.

https://developer.android.com/reference/android/webkit/MimeTypeMap#getFileExtensionFromUrl(java.lang.String) fails to unwrap the URI if there is non-Latin characters.

**Comment by anonymous5555522222** [comment] 2023-10-13 16:48
> Reproduced, will rename the bug report to reflect the issue more precisely

I would like to add that this also happens with files with `'` on their filenames, which means songs with English titles are also affected.

**Comment by soncaokim** [comment] 2023-10-13 17:11
The issue is fixed with the above PR.
Thanks for reporting this, and helping me to troubleshoot.

**Closed** 2023-10-13 18:14 UTC
Labels: bug, reproduced
