### ISSUE TITLE
Crashing when scanning files

### ISSUE THREAD

**Issue by hibonox705** [VinylMusicPlayer/VinylMusicPlayer#837] opened 2023-10-28 11:16 UTC
**Describe the bug**
The app crashed during the scanning of the audio files I have on my device 
**To reproduce**
Just installed the app, accepted the authorizations and waited during the scan of my files 

**Expected behavior**
Scanning throughout my phone and showing the files

**Device info**
App version: 1.5.5
App version code: 184
Android build version: V14.0.12.0.TKOCNXM
Android release version: 13
Android SDK version: 33
Android build ID: TKQ1.220829.002 release-keys
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: lisa
Device model: 2109119DG
Device product name: lisa
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

Time: Sat Oct 28 13:09:02 GMT+02:00 2023

Stack:
java.lang.IllegalStateException: Can't access ViewModels from detached fragment
	at androidx.fragment.app.Fragment.getViewModelStore(Unknown Source:35)
	at androidx.loader.app.LoaderManager.getInstance(Unknown Source:5)
	at com.poupa.vinylmusicplayer.ui.fragments.mainactivity.library.pager.SongsFragment.reload(Unknown Source:0)
	at com.poupa.vinylmusicplayer.discog.b.accept(Unknown Source:20)
	at com.poupa.vinylmusicplayer.helper.WeakMethodReference.run(Unknown Source:10)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loopOnce(Unknown Source:182)
	at android.os.Looper.loop(Unknown Source:82)
	at android.app.ActivityThread.main(Unknown Source:123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:312)

**Comment by soncaokim** [comment] 2023-10-28 12:50
Duplicate of #707

**Closed by soncaokim** 2023-10-28 12:50 UTC
Labels: bug
